databases:
  - name: quickbite-db
    plan: free
    databaseName: quickbite_db
    user: quickbite_user

services:
  - type: web
    name: quickbite-connect
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: quickbite-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False